version: "3"

networks:
  loki:

services:
  promtail:
    image: grafana/promtail:latest
    restart: always
    volumes:
      - /opt/loki/promtail:/etc/promtail
      - /var/log:/var/log
      - /var/lib/docker:/var/lib/docker
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki
